# AIOS Git Hooks Installer
# 用法: .\scripts\hooks\install.ps1
# 将 AIOS 的 git hooks 安装到当前项目的 .git/hooks/ 目录

$ErrorActionPreference = "Stop"
$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Split-Path -Parent (Split-Path -Parent $ScriptRoot)
$GitHooksDir = Join-Path $RepoRoot ".git" "hooks"

if (-not (Test-Path $GitHooksDir)) {
    Write-Host "❌ 未找到 .git/hooks 目录。请在 git 仓库根目录运行此脚本。" -ForegroundColor Red
    exit 1
}

$hooks = @{
    "pre-commit" = "pre-commit.ps1"
    "commit-msg" = "commit-msg.ps1"
}

$installed = 0
foreach ($hook in $hooks.Keys) {
    $source = Join-Path $ScriptRoot "$hook.ps1"
    $target = Join-Path $GitHooksDir $hook

    # 生成 PowerShell launcher 脚本作为 git hook
    $launcher = @"
#!/usr/bin/env pwsh
# AIOS $hook hook (auto-generated by AIOS)
`$ScriptDir = Split-Path -Parent `$MyInvocation.MyCommand.Path
& (Join-Path `$ScriptDir "$hook.ps1") @args
if (`$LASTEXITCODE -ne 0) { exit `$LASTEXITCODE }
"@

    # 复制 hook 脚本到 .git/hooks/
    $hookScriptTarget = Join-Path $GitHooksDir "$hook.ps1"
    Copy-Item $source $hookScriptTarget -Force
    Set-Content -Path $target -Value $launcher -NoNewline

    Write-Host "  ✅ 已安装 $hook hook" -ForegroundColor Green
    $installed++
}

Write-Host "`n=== AIOS Git Hooks 安装完成 ===" -ForegroundColor Cyan
Write-Host "已安装 $installed 个 hook:" -ForegroundColor Green
Write-Host "  - pre-commit: 密钥扫描 + 调试代码检查 + state 检查" -ForegroundColor Gray
Write-Host "  - commit-msg: Conventional Commits 格式校验" -ForegroundColor Gray
