#!/usr/bin/env bash
# AIOS Git Hooks Installer (macOS / Linux)
# 用法: bash scripts/hooks/install.sh
# 将 AIOS 的 git hooks 安装到当前项目的 .git/hooks/ 目录

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GIT_HOOKS_DIR="$REPO_ROOT/.git/hooks"

if [ ! -d "$GIT_HOOKS_DIR" ]; then
    echo "  x .git/hooks not found. Run from a git repository root."
    exit 1
fi

INSTALLED=0

for hook in pre-commit commit-msg; do
    SOURCE="$SCRIPT_DIR/$hook.sh"
    TARGET="$GIT_HOOKS_DIR/$hook"

    if [ ! -f "$SOURCE" ]; then
        echo "  ! $hook.sh not found in $SCRIPT_DIR"
        continue
    fi

    # Copy hook script
    cp "$SOURCE" "$GIT_HOOKS_DIR/$hook.sh"
    chmod +x "$GIT_HOOKS_DIR/$hook.sh"

    # Create git hook launcher
    cat > "$TARGET" << LAUNCHER
#!/usr/bin/env bash
# AIOS $hook hook (auto-generated by AIOS)
HOOK_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
exec bash "\$HOOK_DIR/$hook.sh" "\$@"
LAUNCHER
    chmod +x "$TARGET"

    echo "  + Installed $hook hook"
    INSTALLED=$((INSTALLED+1))
done

echo -e "\n=== AIOS Git Hooks Installed ==="
echo "Installed $INSTALLED hooks:"
echo "  - pre-commit: secret scan + debug code check"
echo "  - commit-msg: Conventional Commits format check"
